name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ github.token }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4 
      - name: Build  
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Lint:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Execute Linting
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  
  Docker:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps: 
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: build docker
        run: bash ci/build-docker.sh
      - name: push docker
        run: bash ci/push-docker.sh
